# Develop quick stuff

For temporary/quick stuff to be developed

In [8]:
import sys
import os

base_path = os.path.abspath("./..")
if base_path not in sys.path:
    sys.path.append(base_path)

In [15]:
%run  compare_torchlogit


Beginning binary comparision:
	Step 0: Estimation
		0. GLM:
			Time needed: 94.64 (ns)
		1. scikit learn
			Time needed: 72.17 (ns)
		2. torch implementation
			Time needed: 201.29 (ms)
	Step 1: Parameter Comparision. Order (GLM), Sklearn, torch
		Comparision of weights
tensor([[-0.245357, -2.796568,  1.313643, -2.778344],
        [-0.243807, -2.794396,  1.312129, -2.775625],
        [-0.245356, -2.796563,  1.313646, -2.778350]])

		Comparision of intercept
tensor([[7.378487],
        [7.365500],
        [7.378466]])
	Step 2: Comparision of predicted probabilities.
		Randomly chosen probs:
tensor([[[0.946796, 0.053204],
         [0.946710, 0.053290],
         [0.946796, 0.053204]],

        [[0.218185, 0.781815],
         [0.218615, 0.781385],
         [0.218186, 0.781814]],

        [[0.661200, 0.338800],
         [0.661127, 0.338873],
         [0.661201, 0.338799]],

        [[0.467376, 0.532624],
         [0.467426, 0.532574],
         [0.467377, 0.532623]],

        [[0.765546, 0.

In [12]:
if True:
    if is_binary:
        joint_weights = torch.cat([
            torch.from_numpy(fitted_glm.params[1:]).unsqueeze(0), 
            torch.from_numpy(sk_lr.coef_), 
            torch_lr.lin_estimator.weight.detach()
        ])
    else:
        joint_weights = torch.stack([
            torch.from_numpy(sk_lr.coef_), 
            torch_lr.lin_estimator.weight.detach()
        ], dim = 1)

    print(joint_weights)

tensor([[[  7.347411,  20.367348, -30.209522, -14.118483],
         [  5.344215,  13.557785, -19.684066,  -9.235632]],

        [[ -2.438356,  -6.850090,  10.398220,  -2.074851],
         [ -1.375284,  -3.357254,   4.745635,  -4.885196]],

        [[ -4.909054, -13.517258,  19.811302,  16.193334],
         [ -3.840487, -10.038158,  14.174999,  13.400937]]])
